# Generated by Django 4.2 on 2024-10-01 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=16, verbose_name='Название породы')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=16, verbose_name='Цвет кошки')),
                ('age', models.IntegerField(verbose_name='Возраст кошки')),
                ('description', models.TextField(verbose_name='Описание кошки')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_cat', to='cats.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cat', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кошки')),
            ],
        ),
    ]
